/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xltech_client_service_H264Decoder */

#ifndef _Included_com_xltech_client_service_H264Decoder
#define _Included_com_xltech_client_service_H264Decoder
#ifdef __cplusplus
extern "C" {
#endif

#include "codec_api.h"
#include "codec_def.h"
#include "codec_app_def.h"
#include "codec_ver.h"

typedef struct H264Decoder {
    // for decoder resource(open h264)
    ISVCDecoder *dec;
    unsigned char* data[3];
    SBufferInfo bufInfo;
} H264Decoder;

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    CreateDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xltech_client_service_H264Decoder_CreateDecoder
  (JNIEnv *, jclass);

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    DestroyDecoder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xltech_client_service_H264Decoder_DestroyDecoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    GetWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xltech_client_service_H264Decoder_GetWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    GetHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xltech_client_service_H264Decoder_GetHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    DecodeOneFrame
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xltech_client_service_H264Decoder_DecodeOneFrame
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_xltech_client_service_H264Decoder
 * Method:    GetYUVData
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xltech_client_service_H264Decoder_GetYUVData
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
